In [50]:
import numpy as np
import os
import json
import cv2

In [48]:
datapath = "./data/CityScapes/leftImg8bit_trainvaltest/leftImg8bit/"
annotpath = "./data/CityScapes/gtFine_trainvaltest/gtFine/"


dt = []


In [49]:
f = open("data/CityScapes/data_list.txt", "a")
for sett in os.listdir(datapath):
    for loc in os.listdir(datapath+sett):
        for im_nm in os.listdir(datapath+sett +"/"+loc):
            s = im_nm.split("_")
            s = "_".join(s[:3])
            with open(annotpath + sett + "/" + loc + "/" + s + "_" + "gtFine_polygons.json") as fl:
                annot = json.load(fl)
                for item in  annot["objects"]:
                    pgs = np.array(item["polygon"])
                    lbl  = item["label"]
                    x1, y1 =  np.min(pgs, axis=0)
                    x2, y2 =  np.max(pgs, axis=0)
                    l = [datapath+sett +"/"+loc + "/" + im_nm, x1, y1, x2, y2, lbl]
                    f.write(",".join(map(str, l)) + "\n")
f.close()

In [43]:
dt

[['./data/CityScapes/leftImg8bit_trainvaltest/leftImg8bit/test/berlin/berlin_000000_000019_leftImg8bit.png',
  271,
  844,
  2028,
  1023,
  u'ego vehicle'],
 ['./data/CityScapes/leftImg8bit_trainvaltest/leftImg8bit/test/berlin/berlin_000000_000019_leftImg8bit.png',
  0,
  0,
  2048,
  1024,
  u'out of roi']]

In [60]:
a = cv2.imread('./data/CityScapes/leftImg8bit_trainvaltest/leftImg8bit/test/berlin/berlin_000000_000019_leftImg8bit.png')

In [61]:
print a

[[[34 52 40]
  [34 51 39]
  [34 50 38]
  ..., 
  [17 22 16]
  [16 21 15]
  [15 19 14]]

 [[32 50 38]
  [33 50 39]
  [33 50 37]
  ..., 
  [17 22 16]
  [16 20 14]
  [15 20 14]]

 [[30 48 35]
  [30 48 35]
  [30 47 34]
  ..., 
  [16 21 15]
  [16 20 14]
  [15 19 13]]

 ..., 
 [[32 33 22]
  [32 32 21]
  [34 34 23]
  ..., 
  [31 32 22]
  [30 32 22]
  [30 32 22]]

 [[32 33 22]
  [32 32 21]
  [34 34 23]
  ..., 
  [29 31 22]
  [29 31 22]
  [30 31 23]]

 [[32 33 22]
  [32 32 21]
  [34 34 23]
  ..., 
  [27 27 19]
  [27 27 19]
  [28 28 20]]]
